# Generated by Django 3.1 on 2020-09-30 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='call_mast',
            fields=[
                ('Candidate_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Candidate_name', models.CharField(max_length=255)),
                ('Contact_number', models.CharField(max_length=255)),
                ('Email_id', models.CharField(max_length=255)),
                ('Interested_area', models.CharField(max_length=255)),
                ('Receiving_date', models.DateField()),
            ],
            options={
                'db_table': 'calling master',
            },
        ),
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('Course_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(max_length=100)),
                ('Fees', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceMaster',
            fields=[
                ('Source_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Source_name', models.CharField(max_length=100)),
                ('Rate_per_candidate', models.BigIntegerField()),
                ('Contact_no', models.BigIntegerField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_of_Entry', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='training_trans',
            fields=[
                ('Payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Candidate_name', models.CharField(max_length=100)),
                ('Date_of_transaction', models.DateField()),
                ('Course_amount', models.CharField(max_length=100)),
                ('Payment_mode', models.CharField(max_length=100)),
                ('Amount_deposited', models.CharField(max_length=100)),
                ('Bank_transaction_id', models.CharField(max_length=20)),
                ('Bank_account_number', models.CharField(max_length=20)),
                ('Cheque_number', models.CharField(max_length=100)),
                ('Warning_level', models.CharField(max_length=100)),
                ('Payment_status', models.CharField(max_length=100)),
                ('Reason_for_nonPayment', models.CharField(max_length=100)),
                ('Course_ID', models.ForeignKey(db_column='Course_ID', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='sha_final_app.coursemaster')),
            ],
            options={
                'db_table': 'training transaction',
            },
        ),
        migrations.CreateModel(
            name='CandidateTrainingMaster',
            fields=[
                ('Training_ID', models.AutoField(primary_key=True, serialize=False)),
                ('canname', models.CharField(max_length=100)),
                ('ContactNo', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=250)),
                ('idProofName', models.CharField(max_length=250)),
                ('idProofNo', models.CharField(max_length=250)),
                ('dateOfBirth', models.DateField()),
                ('Placement', models.CharField(max_length=250)),
                ('callId', models.IntegerField()),
                ('Address', models.TextField()),
                ('parentName', models.CharField(max_length=250)),
                ('offerId', models.IntegerField()),
                ('ParentCont', models.CharField(max_length=250)),
                ('dateOfReg', models.DateField()),
                ('Status', models.CharField(max_length=250)),
                ('paymentDueDay', models.DateField()),
                ('noOfInstallments', models.IntegerField()),
                ('Date_of_entry', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('Candidate_ID', models.ForeignKey(db_column='Candidate_ID', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='sha_final_app.call_mast')),
                ('Course_ID', models.ForeignKey(db_column='Course_ID', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='sha_final_app.coursemaster')),
            ],
        ),
        migrations.CreateModel(
            name='call_trans',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('Feedback', models.CharField(max_length=100)),
                ('Next_Call_Date', models.DateField()),
                ('Next_Call_Time', models.TimeField()),
                ('Cofirm', models.CharField(max_length=100)),
                ('Call_Date', models.DateField()),
                ('Call_Time', models.TimeField()),
                ('Candidate_ID', models.ForeignKey(db_column='Candidate_ID', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='sha_final_app.call_mast')),
            ],
            options={
                'db_table': 'calling transaction',
            },
        ),
        migrations.AddField(
            model_name='call_mast',
            name='Source_name',
            field=models.ForeignKey(db_column='Source_ID', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='sha_final_app.sourcemaster'),
        ),
    ]
